cc.animationCache = {
    _animations: {},
    addAnimation: function(animation, name) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->4");
    },
    removeAnimation: function(name) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->7");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->8");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->9");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->10");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->11");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->12");
    },
    getAnimation: function(name) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->15");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->16");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->17");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->18");
    },
    _addAnimationsWithDictionary: function(dictionary, plist) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->21");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->22");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->23");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->24");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->25");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->26");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->27");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->28");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->29");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->30");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->31");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->32");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->33");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->34");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->35");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->36");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->37");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->38");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->39");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->40");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->41");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->42");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->43");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->44");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->45");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->46");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->47");
    },
    addAnimations: function(plist) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->50");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->51");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->52");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->53");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->54");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->55");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->56");
    },
    _parseVersion1: function(animations) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->59");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->60");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->61");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->62");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->63");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->64");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->65");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->66");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->67");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->68");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->69");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->70");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->71");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->72");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->73");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->74");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->75");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->76");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->77");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->78");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->79");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->80");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->81");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->82");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->83");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->84");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->85");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->86");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->87");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->88");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->89");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->90");
    },
    _parseVersion2: function(animations) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->93");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->94");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->95");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->96");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->97");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->98");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->99");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->100");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->101");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->102");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->103");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->104");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->105");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->106");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->107");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->108");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->109");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->110");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->111");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->112");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->113");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->114");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->115");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->116");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->117");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->118");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->119");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->120");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->121");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->122");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->123");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->124");
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->125");
    },
    _clear: function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/sprites/CCAnimationCache.js->128");
    }
};