ccui.helper = {
    seekWidgetByTag: function(root, tag) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->3");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->4");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->5");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->6");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->7");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->8");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->9");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->10");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->11");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->12");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->13");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->14");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->15");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->16");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->17");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->18");
    },
    seekWidgetByName: function(root, name) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->21");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->22");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->23");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->24");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->25");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->26");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->27");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->28");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->29");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->30");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->31");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->32");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->33");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->34");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->35");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->36");
    },
    seekWidgetByRelativeName: function(root, name) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->39");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->40");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->41");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->42");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->43");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->44");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->45");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->46");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->47");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->48");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->49");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->50");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->51");
    },
    seekActionWidgetByActionTag: function(root, tag) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->54");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->55");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->56");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->57");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->58");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->59");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->60");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->61");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->62");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->63");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->64");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->65");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->66");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->67");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->68");
    },
    _activeLayout: true,
    doLayout: function(rootNode) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->72");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->73");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->74");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->75");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->76");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->77");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->78");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->79");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->80");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->81");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->82");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->83");
    },
    changeLayoutSystemActiveState: function(active) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->86");
    },
    restrictCapInsetRect: function(capInsets, textureSize) {
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->89");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->90");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->91");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->92");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->93");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->94");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->95");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->96");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->97");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->98");
console.log("/frameworks/cocos2d-html5/extensions/ccui/system/UIHelper.js->99");
    }
};