(function() {
    cc.Layer.CanvasRenderCmd = function(renderable) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->3");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->4");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->5");
    };
    var proto = cc.Layer.CanvasRenderCmd.prototype = Object.create(cc.Node.CanvasRenderCmd.prototype);
    proto.constructor = cc.Layer.CanvasRenderCmd;
    proto.bake = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->10");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->11");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->12");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->13");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->14");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->15");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->16");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->17");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->18");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->19");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->20");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->21");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->22");
    };
    proto.unbake = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->25");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->26");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->27");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->28");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->29");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->30");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->31");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->32");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->33");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->34");
    };
    proto.isBaked = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->37");
    };
    proto.rendering = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->40");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->41");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->42");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->43");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->44");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->45");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->46");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->47");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->48");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->49");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->50");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->51");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->52");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->53");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->54");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->55");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->56");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->57");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->58");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->59");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->60");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->61");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->62");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->63");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->64");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->65");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->66");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->67");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->68");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->69");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->70");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->71");
    };
    proto.visit = function(parentCmd) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->74");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->75");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->76");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->77");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->78");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->79");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->80");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->81");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->82");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->83");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->84");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->85");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->86");
    };
    proto._bakeForAddChild = function(child) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->89");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->90");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->91");
    };
    proto._getBoundingBoxForBake = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->94");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->95");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->96");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->97");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->98");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->99");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->100");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->101");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->102");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->103");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->104");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->105");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->106");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->107");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->108");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->109");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->110");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->111");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->112");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->113");
    };
})();
(function() {
    cc.LayerColor.CanvasRenderCmd = function(renderable) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->118");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->119");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->120");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->121");
    };
    var proto = cc.LayerColor.CanvasRenderCmd.prototype = Object.create(cc.Layer.CanvasRenderCmd.prototype);
    proto.constructor = cc.LayerColor.CanvasRenderCmd;
    proto.unbake = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->126");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->127");
    };
    proto.rendering = function(ctx, scaleX, scaleY) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->130");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->131");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->132");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->133");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->134");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->135");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->136");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->137");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->138");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->139");
    };
    proto.updateBlendFunc = function(blendFunc) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->142");
    };
    proto._updateSquareVertices = proto._updateSquareVerticesWidth = proto._updateSquareVerticesHeight = function() {};
    proto._bakeRendering = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->146");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->147");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->148");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->149");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->150");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->151");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->152");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->153");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->154");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->155");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->156");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->157");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->158");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->159");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->160");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->161");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->162");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->163");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->164");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->165");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->166");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->167");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->168");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->169");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->170");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->171");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->172");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->173");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->174");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->175");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->176");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->177");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->178");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->179");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->180");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->181");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->182");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->183");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->184");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->185");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->186");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->187");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->188");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->189");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->190");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->191");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->192");
    };
    proto.visit = function(parentCmd) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->195");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->196");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->197");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->198");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->199");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->200");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->201");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->202");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->203");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->204");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->205");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->206");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->207");
    };
    proto._getBoundingBoxForBake = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->210");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->211");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->212");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->213");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->214");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->215");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->216");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->217");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->218");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->219");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->220");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->221");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->222");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->223");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->224");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->225");
    };
})();
(function() {
    cc.LayerGradient.RenderCmd = {
        updateStatus: function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->231");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->232");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->233");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->234");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->235");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->236");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->237");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->238");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->239");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->240");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->241");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->242");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->243");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->244");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->245");
        }
    };
})();
(function() {
    cc.LayerGradient.CanvasRenderCmd = function(renderable) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->251");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->252");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->253");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->254");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->255");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->256");
    };
    var proto = cc.LayerGradient.CanvasRenderCmd.prototype = Object.create(cc.LayerColor.CanvasRenderCmd.prototype);
    cc.inject(cc.LayerGradient.RenderCmd, proto);
    proto.constructor = cc.LayerGradient.CanvasRenderCmd;
    proto.rendering = function(ctx, scaleX, scaleY) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->262");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->263");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->264");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->265");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->266");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->267");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->268");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->269");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->270");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->271");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->272");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->273");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->274");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->275");
    };
    proto._syncStatus = function(parentCmd) {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->278");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->279");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->280");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->281");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->282");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->283");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->284");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->285");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->286");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->287");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->288");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->289");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->290");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->291");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->292");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->293");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->294");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->295");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->296");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->297");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->298");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->299");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->300");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->301");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->302");
    };
    proto._updateColor = function() {
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->305");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->306");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->307");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->308");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->309");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->310");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->311");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->312");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->313");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->314");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->315");
console.log("/frameworks/cocos2d-html5/cocos2d/core/layers/CCLayerCanvasRenderCmd.js->316");
    };
})();