ccs.CONST_VERSION = "version";
ccs.CONST_VERSION_2_0 = 2;
ccs.CONST_VERSION_COMBINED = .3;
ccs.CONST_ARMATURES = "armatures";
ccs.CONST_ARMATURE = "armature";
ccs.CONST_BONE = "b";
ccs.CONST_DISPLAY = "d";
ccs.CONST_ANIMATIONS = "animations";
ccs.CONST_ANIMATION = "animation";
ccs.CONST_MOVEMENT = "mov";
ccs.CONST_FRAME = "f";
ccs.CONST_TEXTURE_ATLAS = "TextureAtlas";
ccs.CONST_SUB_TEXTURE = "SubTexture";
ccs.CONST_SKELETON = "skeleton";
ccs.CONST_A_NAME = "name";
ccs.CONST_A_DURATION = "dr";
ccs.CONST_A_FRAME_INDEX = "fi";
ccs.CONST_A_DURATION_TO = "to";
ccs.CONST_A_DURATION_TWEEN = "drTW";
ccs.CONST_A_LOOP = "lp";
ccs.CONST_A_MOVEMENT_SCALE = "sc";
ccs.CONST_A_MOVEMENT_DELAY = "dl";
ccs.CONST_A_DISPLAY_INDEX = "dI";
ccs.CONST_A_PLIST = "plist";
ccs.CONST_A_PARENT = "parent";
ccs.CONST_A_SKEW_X = "kX";
ccs.CONST_A_SKEW_Y = "kY";
ccs.CONST_A_SCALE_X = "cX";
ccs.CONST_A_SCALE_Y = "cY";
ccs.CONST_A_Z = "z";
ccs.CONST_A_EVENT = "evt";
ccs.CONST_A_SOUND = "sd";
ccs.CONST_A_SOUND_EFFECT = "sdE";
ccs.CONST_A_TWEEN_EASING = "twE";
ccs.CONST_A_EASING_PARAM = "twEP";
ccs.CONST_A_TWEEN_ROTATE = "twR";
ccs.CONST_A_IS_ARMATURE = "isArmature";
ccs.CONST_A_DISPLAY_TYPE = "displayType";
ccs.CONST_A_MOVEMENT = "mov";
ccs.CONST_A_X = "x";
ccs.CONST_A_Y = "y";
ccs.CONST_A_COCOS2DX_X = "cocos2d_x";
ccs.CONST_A_COCOS2DX_Y = "cocos2d_y";
ccs.CONST_A_WIDTH = "width";
ccs.CONST_A_HEIGHT = "height";
ccs.CONST_A_PIVOT_X = "pX";
ccs.CONST_A_PIVOT_Y = "pY";
ccs.CONST_A_COCOS2D_PIVOT_X = "cocos2d_pX";
ccs.CONST_A_COCOS2D_PIVOT_Y = "cocos2d_pY";
ccs.CONST_A_BLEND_TYPE = "bd";
ccs.CONST_A_BLEND_SRC = "bd_src";
ccs.CONST_A_BLEND_DST = "bd_dst";
ccs.CONST_A_ALPHA = "a";
ccs.CONST_A_RED = "r";
ccs.CONST_A_GREEN = "g";
ccs.CONST_A_BLUE = "b";
ccs.CONST_A_ALPHA_OFFSET = "aM";
ccs.CONST_A_RED_OFFSET = "rM";
ccs.CONST_A_GREEN_OFFSET = "gM";
ccs.CONST_A_BLUE_OFFSET = "bM";
ccs.CONST_A_COLOR_TRANSFORM = "colorTransform";
ccs.CONST_A_TWEEN_FRAME = "tweenFrame";
ccs.CONST_CONTOUR = "con";
ccs.CONST_CONTOUR_VERTEX = "con_vt";
ccs.CONST_FL_NAN = "NaN";
ccs.CONST_FRAME_DATA = "frame_data";
ccs.CONST_MOVEMENT_BONE_DATA = "mov_bone_data";
ccs.CONST_MOVEMENT_DATA = "mov_data";
ccs.CONST_ANIMATION_DATA = "animation_data";
ccs.CONST_DISPLAY_DATA = "display_data";
ccs.CONST_SKIN_DATA = "skin_data";
ccs.CONST_BONE_DATA = "bone_data";
ccs.CONST_ARMATURE_DATA = "armature_data";
ccs.CONST_CONTOUR_DATA = "contour_data";
ccs.CONST_TEXTURE_DATA = "texture_data";
ccs.CONST_VERTEX_POINT = "vertex";
ccs.CONST_COLOR_INFO = "color";
ccs.CONST_CONFIG_FILE_PATH = "config_file_path";
ccs.CONST_CONTENT_SCALE = "content_scale";
ccs.DataInfo = function() {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->81");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->82");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->83");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->84");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->85");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->86");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->87");
};
ccs.dataReaderHelper = {
    ConfigType: {
        DragonBone_XML: 0,
        CocoStudio_JSON: 1,
        CocoStudio_Binary: 2
    },
    _configFileList: [],
    _flashToolVersion: ccs.CONST_VERSION_2_0,
    _positionReadScale: 1,
    _asyncRefCount: 0,
    _asyncRefTotalCount: 0,
    _dataQueue: null,
    setPositionReadScale: function(scale) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->102");
    },
    getPositionReadScale: function() {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->105");
    },
    addDataFromFile: function(filePath) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->108");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->109");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->110");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->111");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->112");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->113");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->114");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->115");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->116");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->117");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->118");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->119");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->120");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->121");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->122");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->123");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->124");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->125");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->126");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->127");
    },
    addDataFromFileAsync: function(imagePath, plistPath, filePath, selector, target) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->130");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->131");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->132");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->133");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->134");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->135");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->136");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->137");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->138");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->139");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->140");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->141");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->142");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->143");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->144");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->145");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->146");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->147");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->148");
    },
    removeConfigFile: function(configFile) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->151");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->152");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->153");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->154");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->155");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->156");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->157");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->158");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->159");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->160");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->161");
    },
    addDataFromCache: function(skeleton, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->164");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->165");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->166");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->167");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->168");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->169");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->170");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->171");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->172");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->173");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->174");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->175");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->176");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->177");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->178");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->179");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->180");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->181");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->182");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->183");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->184");
    },
    decodeArmature: function(armatureXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->187");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->188");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->189");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->190");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->191");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->192");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->193");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->194");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->195");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->196");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->197");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->198");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->199");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->200");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->201");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->202");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->203");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->204");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->205");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->206");
    },
    decodeArmatureFromJSON: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->209");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->210");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->211");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->212");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->213");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->214");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->215");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->216");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->217");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->218");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->219");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->220");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->221");
    },
    decodeBone: function(boneXML, parentXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->224");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->225");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->226");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->227");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->228");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->229");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->230");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->231");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->232");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->233");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->234");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->235");
    },
    decodeBoneFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->238");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->239");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->240");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->241");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->242");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->243");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->244");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->245");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->246");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->247");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->248");
    },
    decodeBoneDisplay: function(displayXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->251");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->252");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->253");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->254");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->255");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->256");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->257");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->258");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->259");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->260");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->261");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->262");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->263");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->264");
    },
    decodeBoneDisplayFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->267");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->268");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->269");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->270");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->271");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->272");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->273");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->274");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->275");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->276");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->277");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->278");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->279");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->280");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->281");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->282");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->283");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->284");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->285");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->286");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->287");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->288");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->289");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->290");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->291");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->292");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->293");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->294");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->295");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->296");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->297");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->298");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->299");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->300");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->301");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->302");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->303");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->304");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->305");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->306");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->307");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->308");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->309");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->310");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->311");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->312");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->313");
    },
    decodeAnimation: function(animationXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->316");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->317");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->318");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->319");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->320");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->321");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->322");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->323");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->324");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->325");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->326");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->327");
    },
    decodeAnimationFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->330");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->331");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->332");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->333");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->334");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->335");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->336");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->337");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->338");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->339");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->340");
    },
    decodeMovement: function(movementXML, armatureData, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->343");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->344");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->345");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->346");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->347");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->348");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->349");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->350");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->351");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->352");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->353");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->354");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->355");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->356");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->357");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->358");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->359");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->360");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->361");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->362");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->363");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->364");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->365");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->366");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->367");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->368");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->369");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->370");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->371");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->372");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->373");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->374");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->375");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->376");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->377");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->378");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->379");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->380");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->381");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->382");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->383");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->384");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->385");
    },
    decodeMovementFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->388");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->389");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->390");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->391");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->392");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->393");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->394");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->395");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->396");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->397");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->398");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->399");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->400");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->401");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->402");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->403");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->404");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->405");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->406");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->407");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->408");
    },
    decodeMovementBone: function(movBoneXml, parentXml, boneData, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->411");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->412");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->413");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->414");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->415");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->416");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->417");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->418");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->419");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->420");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->421");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->422");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->423");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->424");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->425");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->426");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->427");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->428");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->429");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->430");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->431");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->432");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->433");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->434");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->435");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->436");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->437");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->438");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->439");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->440");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->441");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->442");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->443");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->444");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->445");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->446");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->447");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->448");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->449");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->450");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->451");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->452");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->453");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->454");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->455");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->456");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->457");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->458");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->459");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->460");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->461");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->462");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->463");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->464");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->465");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->466");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->467");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->468");
    },
    decodeMovementBoneFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->471");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->472");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->473");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->474");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->475");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->476");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->477");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->478");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->479");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->480");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->481");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->482");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->483");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->484");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->485");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->486");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->487");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->488");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->489");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->490");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->491");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->492");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->493");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->494");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->495");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->496");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->497");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->498");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->499");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->500");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->501");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->502");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->503");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->504");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->505");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->506");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->507");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->508");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->509");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->510");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->511");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->512");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->513");
    },
    decodeFrame: function(frameXML, parentFrameXml, boneData, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->516");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->517");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->518");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->519");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->520");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->521");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->522");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->523");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->524");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->525");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->526");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->527");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->528");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->529");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->530");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->531");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->532");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->533");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->534");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->535");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->536");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->537");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->538");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->539");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->540");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->541");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->542");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->543");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->544");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->545");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->546");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->547");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->548");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->549");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->550");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->551");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->552");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->553");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->554");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->555");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->556");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->557");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->558");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->559");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->560");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->561");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->562");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->563");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->564");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->565");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->566");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->567");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->568");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->569");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->570");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->571");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->572");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->573");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->574");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->575");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->576");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->577");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->578");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->579");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->580");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->581");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->582");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->583");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->584");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->585");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->586");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->587");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->588");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->589");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->590");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->591");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->592");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->593");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->594");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->595");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->596");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->597");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->598");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->599");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->600");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->601");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->602");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->603");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->604");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->605");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->606");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->607");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->608");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->609");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->610");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->611");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->612");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->613");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->614");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->615");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->616");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->617");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->618");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->619");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->620");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->621");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->622");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->623");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->624");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->625");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->626");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->627");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->628");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->629");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->630");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->631");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->632");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->633");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->634");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->635");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->636");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->637");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->638");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->639");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->640");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->641");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->642");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->643");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->644");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->645");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->646");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->647");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->648");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->649");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->650");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->651");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->652");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->653");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->654");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->655");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->656");
    },
    decodeFrameFromJson: function(json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->659");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->660");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->661");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->662");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->663");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->664");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->665");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->666");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->667");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->668");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->669");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->670");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->671");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->672");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->673");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->674");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->675");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->676");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->677");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->678");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->679");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->680");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->681");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->682");
    },
    decodeTexture: function(textureXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->685");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->686");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->687");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->688");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->689");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->690");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->691");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->692");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->693");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->694");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->695");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->696");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->697");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->698");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->699");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->700");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->701");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->702");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->703");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->704");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->705");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->706");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->707");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->708");
    },
    decodeTextureFromJson: function(json) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->711");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->712");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->713");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->714");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->715");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->716");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->717");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->718");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->719");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->720");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->721");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->722");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->723");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->724");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->725");
    },
    decodeContour: function(contourXML, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->728");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->729");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->730");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->731");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->732");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->733");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->734");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->735");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->736");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->737");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->738");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->739");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->740");
    },
    decodeContourFromJson: function(json) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->743");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->744");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->745");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->746");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->747");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->748");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->749");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->750");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->751");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->752");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->753");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->754");
    },
    addDataFromJsonCache: function(dic, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->757");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->758");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->759");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->760");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->761");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->762");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->763");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->764");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->765");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->766");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->767");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->768");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->769");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->770");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->771");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->772");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->773");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->774");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->775");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->776");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->777");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->778");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->779");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->780");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->781");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->782");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->783");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->784");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->785");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->786");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->787");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->788");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->789");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->790");
    },
    decodeNodeFromJson: function(node, json, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->793");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->794");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->795");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->796");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->797");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->798");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->799");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->800");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->801");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->802");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->803");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->804");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->805");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->806");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->807");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->808");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->809");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->810");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->811");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->812");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->813");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->814");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->815");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->816");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->817");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->818");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->819");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->820");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->821");
    },
    clear: function() {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->824");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->825");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->826");
    },
    _asyncCallBack: function(selector, target, percent) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->829");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->830");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->831");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->832");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->833");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->834");
    },
    _initBaseFilePath: function(filePath) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->837");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->838");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->839");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->840");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->841");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->842");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->843");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->844");
    },
    addDataFromXML: function(xml, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->847");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->848");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->849");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->850");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->851");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->852");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->853");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->854");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->855");
    },
    addDataFromJson: function(filePath, dataInfo) {
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->858");
console.log("/frameworks/cocos2d-html5/extensions/cocostudio/armature/utils/CCDataReaderHelper.js->859");
    }
};